version: "3"

services:
  data_backend:
    build:
      context: ecowas/
      dockerfile: Dockerfile
    container_name: data_backend
    restart: on-failure
    networks:
      - ecowas_network
    depends_on:
      - postgres

  ecowas-backend:
    build:
      context: ecowas-backend/
      dockerfile: Dockerfile
    container_name: ecowas-backend
    restart: on-failure
    ports:
      - "5000:5000"
    networks:
      - ecowas_network
    depends_on:
      - data_backend

  ecowas-frontend:
    build:
      context: ecowas-frontend/
      dockerfile: Dockerfile
    container_name: ecowas-frontend
    restart: on-failure
    ports:
      - "3000:3000"
    networks:
      - ecowas_network
    depends_on:
      - ecowas-backend

  postgres:
    image: postgres:15.3-alpine3.18
    container_name: ecowas_pg
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data:rw
    env_file: "ecowas/.env"
    networks:
      - ecowas_network

  adminer:
    image: adminer
    container_name: ecowas_adminer
    restart: always
    ports:
      - "8080:8080"
    env_file: "ecowas/.env"
    volumes:
      - pgadmin:/var/lib/pgadmin:rw
    networks:
      - ecowas_network
    depends_on:
      - postgres

volumes:
  data:
  pgadmin:

networks:
  ecowas_network:
    driver: bridge
